export * from './ui/AppShell';
export * from './ui/Sidebar';
export * from './ui/Inspector';
export * from './ui/TitleBar';
export * from './ui/ActivityBar';
export * from './ui/Console';
export * from './ui/StatusBar';
export * from './ui/EditorTabs';
export * from './ui/WorkbenchToolbar';
export * from './ui/AIPanel';
export * from './ui/CommandPalette';
export * from './ui/SelectionOverlay';
export * from './ui/CanvasToolRail';
export * from './ui/CanvasMinimap';
export * from './ui/CanvasZoomHud';
export * from './ui/DevicePreviewBar';
export * from './ui/PageCanvasRenderer';

export * from './panels';
export * from './persistence';

export * from './hooks/useResize';
export * from './hooks/useSelectionSync';
export * from './hooks/useNodePatchDispatch';
export * from './hooks/useCanvasEditingCommands';
export * from './hooks/useShellModeUrl';
export * from './hooks/useEditorSession';
export * from './hooks/useScenarioSession';
export * from './hooks/useEditorHostBridge';
export * from './hooks/useHostCommandPolicy';
export * from './hooks/useTabManager';
export * from './hooks/useWorkspaceHost';
export * from './hooks/useWorkspacePersistence';
export * from './hooks/useCanvasZoom';
export * from './hooks/useCanvasPan';
export * from './hooks/useCanvasDragDrop';
export * from './canvas/types';
export * from './canvas/constants';
export * from './canvas/page-minimap-model';
export { CanvasSurface } from './canvas/CanvasSurface';
export { resolveNodeDropIndicator, type CanvasDropIndicator } from './canvas/drop-indicator';

export * from './ai/editor-ai-bridge';
export * from './ai/useEditorAIBridge';
export * from './commands/generation-lock';
export * from './plugins';
export * from './plugins/host-plugin-registrations';
export * from './plugins/use-plugin-context';
