import type { TestCase } from './types';

/**
 * 组件测试用例 - L1 级别（单属性测试）
 */
export const componentCasesL1: TestCase[] = [
  // ==================== Button ====================
  {
    id: 'button-001',
    name: 'Button - 基础按钮',
    category: 'component',
    subCategory: 'Button',
    level: 'L1',
    prompt: '创建一个_primary_类型的按钮，显示文本"提交"',
    expectedComponent: 'Button',
    expectedProps: ['type'],
  },
  {
    id: 'button-002',
    name: 'Button - 危险按钮',
    category: 'component',
    subCategory: 'Button',
    level: 'L1',
    prompt: '创建一个 danger 模式的按钮',
    expectedComponent: 'Button',
    expectedProps: ['danger'],
  },
  {
    id: 'button-003',
    name: 'Button - 加载中按钮',
    category: 'component',
    subCategory: 'Button',
    level: 'L1',
    prompt: '创建一个加载中状态的按钮',
    expectedComponent: 'Button',
    expectedProps: ['loading'],
  },
  {
    id: 'button-004',
    name: 'Button - 禁用按钮',
    category: 'component',
    subCategory: 'Button',
    level: 'L1',
    prompt: '创建一个禁用的按钮',
    expectedComponent: 'Button',
    expectedProps: ['disabled'],
  },
  {
    id: 'button-005',
    name: 'Button - 块级按钮',
    category: 'component',
    subCategory: 'Button',
    level: 'L1',
    prompt: '创建一个块级按钮，宽度占满父容器',
    expectedComponent: 'Button',
    expectedProps: ['block'],
  },
  {
    id: 'button-006',
    name: 'Button - 圆形按钮',
    category: 'component',
    subCategory: 'Button',
    level: 'L1',
    prompt: '创建一个圆形形状的按钮',
    expectedComponent: 'Button',
    expectedProps: ['shape'],
  },

  // ==================== Input ====================
  {
    id: 'input-001',
    name: 'Input - 基础输入框',
    category: 'component',
    subCategory: 'Input',
    level: 'L1',
    prompt: '创建一个文本输入框，占位符为"请输入用户名"',
    expectedComponent: 'Input',
    expectedProps: ['placeholder'],
  },
  {
    id: 'input-002',
    name: 'Input - 密码输入框',
    category: 'component',
    subCategory: 'Input',
    level: 'L1',
    prompt: '创建一个密码输入框，输入内容应被隐藏',
    expectedComponent: 'Input',
    expectedProps: ['type'],
  },
  {
    id: 'input-003',
    name: 'Input - 带清除按钮的输入框',
    category: 'component',
    subCategory: 'Input',
    level: 'L1',
    prompt: '创建一个带清除按钮的输入框',
    expectedComponent: 'Input',
    expectedProps: ['allowClear'],
  },
  {
    id: 'input-004',
    name: 'Input - 禁用输入框',
    category: 'component',
    subCategory: 'Input',
    level: 'L1',
    prompt: '创建一个禁用的输入框',
    expectedComponent: 'Input',
    expectedProps: ['disabled'],
  },
  {
    id: 'input-005',
    name: 'Input - 限制长度的输入框',
    category: 'component',
    subCategory: 'Input',
    level: 'L1',
    prompt: '创建一个最大长度为 50 的输入框',
    expectedComponent: 'Input',
    expectedProps: ['maxLength'],
  },
  {
    id: 'input-006',
    name: 'Input - 带前缀的输入框',
    category: 'component',
    subCategory: 'Input',
    level: 'L1',
    prompt: '创建一个带用户图标前缀的输入框',
    expectedComponent: 'Input',
    expectedProps: ['prefix'],
  },

  // ==================== Select ====================
  {
    id: 'select-001',
    name: 'Select - 基础选择器',
    category: 'component',
    subCategory: 'Select',
    level: 'L1',
    prompt: '创建一个下拉选择器，选项为 ["选项 1", "选项 2", "选项 3"]',
    expectedComponent: 'Select',
    expectedProps: ['options'],
  },
  {
    id: 'select-002',
    name: 'Select - 禁用选择器',
    category: 'component',
    subCategory: 'Select',
    level: 'L1',
    prompt: '创建一个禁用的下拉选择器',
    expectedComponent: 'Select',
    expectedProps: ['disabled'],
  },
  {
    id: 'select-003',
    name: 'Select - 可搜索选择器',
    category: 'component',
    subCategory: 'Select',
    level: 'L1',
    prompt: '创建一个支持搜索的下拉选择器',
    expectedComponent: 'Select',
    expectedProps: ['showSearch'],
  },
  {
    id: 'select-004',
    name: 'Select - 多选选择器',
    category: 'component',
    subCategory: 'Select',
    level: 'L1',
    prompt: '创建一个支持多选的下拉选择器',
    expectedComponent: 'Select',
    expectedProps: ['mode'],
  },
  {
    id: 'select-005',
    name: 'Select - 带占位符的选择器',
    category: 'component',
    subCategory: 'Select',
    level: 'L1',
    prompt: '创建一个占位符为"请选择"的下拉选择器',
    expectedComponent: 'Select',
    expectedProps: ['placeholder'],
  },

  // ==================== Radio ====================
  {
    id: 'radio-001',
    name: 'Radio - 基础单选框',
    category: 'component',
    subCategory: 'Radio',
    level: 'L1',
    prompt: '创建一个单选按钮，标签为"选项 A"',
    expectedComponent: 'Radio',
    expectedProps: [],
  },
  {
    id: 'radio-002',
    name: 'Radio - 禁用单选框',
    category: 'component',
    subCategory: 'Radio',
    level: 'L1',
    prompt: '创建一个禁用的单选按钮',
    expectedComponent: 'Radio',
    expectedProps: ['disabled'],
  },
  {
    id: 'radio-group-001',
    name: 'Radio.Group - 单选组',
    category: 'component',
    subCategory: 'Radio.Group',
    level: 'L1',
    prompt: '创建一个单选按钮组，包含三个选项',
    expectedComponent: 'Radio.Group',
    expectedProps: ['options'],
  },

  // ==================== Checkbox ====================
  {
    id: 'checkbox-001',
    name: 'Checkbox - 基础复选框',
    category: 'component',
    subCategory: 'Checkbox',
    level: 'L1',
    prompt: '创建一个复选框，标签为"同意协议"',
    expectedComponent: 'Checkbox',
    expectedProps: [],
  },
  {
    id: 'checkbox-002',
    name: 'Checkbox - 禁用复选框',
    category: 'component',
    subCategory: 'Checkbox',
    level: 'L1',
    prompt: '创建一个禁用的复选框',
    expectedComponent: 'Checkbox',
    expectedProps: ['disabled'],
  },
  {
    id: 'checkbox-group-001',
    name: 'Checkbox.Group - 复选组',
    category: 'component',
    subCategory: 'Checkbox.Group',
    level: 'L1',
    prompt: '创建一个复选框组，包含多个选项',
    expectedComponent: 'Checkbox.Group',
    expectedProps: ['options'],
  },

  // ==================== Switch ====================
  {
    id: 'switch-001',
    name: 'Switch - 基础开关',
    category: 'component',
    subCategory: 'Switch',
    level: 'L1',
    prompt: '创建一个开关组件',
    expectedComponent: 'Switch',
    expectedProps: [],
  },
  {
    id: 'switch-002',
    name: 'Switch - 禁用开关',
    category: 'component',
    subCategory: 'Switch',
    level: 'L1',
    prompt: '创建一个禁用的开关',
    expectedComponent: 'Switch',
    expectedProps: ['disabled'],
  },
  {
    id: 'switch-003',
    name: 'Switch - 小尺寸开关',
    category: 'component',
    subCategory: 'Switch',
    level: 'L1',
    prompt: '创建一个小型尺寸的开关',
    expectedComponent: 'Switch',
    expectedProps: ['size'],
  },

  // ==================== Slider ====================
  {
    id: 'slider-001',
    name: 'Slider - 基础滑块',
    category: 'component',
    subCategory: 'Slider',
    level: 'L1',
    prompt: '创建一个滑动输入组件，范围 0-100',
    expectedComponent: 'Slider',
    expectedProps: ['min', 'max'],
  },
  {
    id: 'slider-002',
    name: 'Slider - 范围滑块',
    category: 'component',
    subCategory: 'Slider',
    level: 'L1',
    prompt: '创建一个双滑块范围选择器',
    expectedComponent: 'Slider',
    expectedProps: ['range'],
  },
  {
    id: 'slider-003',
    name: 'Slider - 带刻度的滑块',
    category: 'component',
    subCategory: 'Slider',
    level: 'L1',
    prompt: '创建一个带刻度标记的滑块',
    expectedComponent: 'Slider',
    expectedProps: ['dots'],
  },

  // ==================== Form ====================
  {
    id: 'form-001',
    name: 'Form - 基础表单',
    category: 'component',
    subCategory: 'Form',
    level: 'L1',
    prompt: '创建一个水平布局的表单',
    expectedComponent: 'Form',
    expectedProps: ['layout'],
  },
  {
    id: 'form-002',
    name: 'Form - 垂直表单',
    category: 'component',
    subCategory: 'Form',
    level: 'L1',
    prompt: '创建一个垂直布局的表单',
    expectedComponent: 'Form',
    expectedProps: ['layout'],
  },
  {
    id: 'form-item-001',
    name: 'Form.Item - 表单项',
    category: 'component',
    subCategory: 'Form.Item',
    level: 'L1',
    prompt: '创建一个标签为"用户名"的表单项，字段名为 username',
    expectedComponent: 'Form.Item',
    expectedProps: ['label', 'name'],
  },
  {
    id: 'form-item-002',
    name: 'Form.Item - 必填项',
    category: 'component',
    subCategory: 'Form.Item',
    level: 'L1',
    prompt: '创建一个必填的表单项',
    expectedComponent: 'Form.Item',
    expectedProps: ['rules'],
  },
  {
    id: 'form-item-003',
    name: 'Form.Item - 带验证规则',
    category: 'component',
    subCategory: 'Form.Item',
    level: 'L1',
    prompt: '创建一个带邮箱验证规则的表单项',
    expectedComponent: 'Form.Item',
    expectedProps: ['rules'],
  },

  // ==================== Table ====================
  {
    id: 'table-001',
    name: 'Table - 基础表格',
    category: 'component',
    subCategory: 'Table',
    level: 'L1',
    prompt: '创建一个数据表格，显示用户列表',
    expectedComponent: 'Table',
    expectedProps: ['dataSource', 'columns'],
  },
  {
    id: 'table-002',
    name: 'Table - 带边框表格',
    category: 'component',
    subCategory: 'Table',
    level: 'L1',
    prompt: '创建一个带边框的表格',
    expectedComponent: 'Table',
    expectedProps: ['bordered'],
  },
  {
    id: 'table-003',
    name: 'Table - 加载中表格',
    category: 'component',
    subCategory: 'Table',
    level: 'L1',
    prompt: '创建一个显示加载中状态的表格',
    expectedComponent: 'Table',
    expectedProps: ['loading'],
  },
  {
    id: 'table-004',
    name: 'Table - 带分页表格',
    category: 'component',
    subCategory: 'Table',
    level: 'L1',
    prompt: '创建一个带分页功能的表格',
    expectedComponent: 'Table',
    expectedProps: ['pagination'],
  },

  // ==================== Card ====================
  {
    id: 'card-001',
    name: 'Card - 基础卡片',
    category: 'component',
    subCategory: 'Card',
    level: 'L1',
    prompt: '创建一个卡片容器，标题为"用户信息"',
    expectedComponent: 'Card',
    expectedProps: ['title'],
  },
  {
    id: 'card-002',
    name: 'Card - 带操作卡片',
    category: 'component',
    subCategory: 'Card',
    level: 'L1',
    prompt: '创建一个带操作按钮的卡片',
    expectedComponent: 'Card',
    expectedProps: ['extra'],
  },
  {
    id: 'card-003',
    name: 'Card - 加载中卡片',
    category: 'component',
    subCategory: 'Card',
    level: 'L1',
    prompt: '创建一个加载中状态的卡片',
    expectedComponent: 'Card',
    expectedProps: ['loading'],
  },
  {
    id: 'card-004',
    name: 'Card - 悬停效果卡片',
    category: 'component',
    subCategory: 'Card',
    level: 'L1',
    prompt: '创建一个鼠标悬停时有阴影效果的卡片',
    expectedComponent: 'Card',
    expectedProps: ['hoverable'],
  },

  // ==================== Modal ====================
  {
    id: 'modal-001',
    name: 'Modal - 基础弹窗',
    category: 'component',
    subCategory: 'Modal',
    level: 'L1',
    prompt: '创建一个模态弹窗，标题为"确认"',
    expectedComponent: 'Modal',
    expectedProps: ['title'],
  },
  {
    id: 'modal-002',
    name: 'Modal - 确认弹窗',
    category: 'component',
    subCategory: 'Modal',
    level: 'L1',
    prompt: '创建一个确认对话框，显示确定和取消按钮',
    expectedComponent: 'Modal',
    expectedProps: ['onOk', 'onCancel'],
  },
  {
    id: 'modal-003',
    name: 'Modal - 居中弹窗',
    category: 'component',
    subCategory: 'Modal',
    level: 'L1',
    prompt: '创建一个垂直居中显示的弹窗',
    expectedComponent: 'Modal',
    expectedProps: ['centered'],
  },

  // ==================== Drawer ====================
  {
    id: 'drawer-001',
    name: 'Drawer - 基础抽屉',
    category: 'component',
    subCategory: 'Drawer',
    level: 'L1',
    prompt: '创建一个从右侧滑出的抽屉，标题为"详情"',
    expectedComponent: 'Drawer',
    expectedProps: ['title'],
  },
  {
    id: 'drawer-002',
    name: 'Drawer - 左侧抽屉',
    category: 'component',
    subCategory: 'Drawer',
    level: 'L1',
    prompt: '创建一个从左侧滑出的抽屉',
    expectedComponent: 'Drawer',
    expectedProps: ['placement'],
  },

  // ==================== Alert ====================
  {
    id: 'alert-001',
    name: 'Alert - 成功提示',
    category: 'component',
    subCategory: 'Alert',
    level: 'L1',
    prompt: '创建一个成功类型的提示框',
    expectedComponent: 'Alert',
    expectedProps: ['type'],
  },
  {
    id: 'alert-002',
    name: 'Alert - 错误提示',
    category: 'component',
    subCategory: 'Alert',
    level: 'L1',
    prompt: '创建一个错误类型的提示框',
    expectedComponent: 'Alert',
    expectedProps: ['type'],
  },
  {
    id: 'alert-003',
    name: 'Alert - 带描述提示',
    category: 'component',
    subCategory: 'Alert',
    level: 'L1',
    prompt: '创建一个带辅助描述的提示框',
    expectedComponent: 'Alert',
    expectedProps: ['description'],
  },

  // ==================== Tabs ====================
  {
    id: 'tabs-001',
    name: 'Tabs - 基础标签页',
    category: 'component',
    subCategory: 'Tabs',
    level: 'L1',
    prompt: '创建一个标签页组件，包含两个标签',
    expectedComponent: 'Tabs',
    expectedProps: [],
  },
  {
    id: 'tabs-002',
    name: 'Tabs - 卡片风格',
    category: 'component',
    subCategory: 'Tabs',
    level: 'L1',
    prompt: '创建一个卡片风格的标签页',
    expectedComponent: 'Tabs',
    expectedProps: ['type'],
  },
  {
    id: 'tabs-003',
    name: 'Tabs - 底部标签',
    category: 'component',
    subCategory: 'Tabs',
    level: 'L1',
    prompt: '创建一个标签在底部的组件',
    expectedComponent: 'Tabs',
    expectedProps: ['tabPosition'],
  },

  // ==================== DatePicker ====================
  {
    id: 'datepicker-001',
    name: 'DatePicker - 基础日期选择',
    category: 'component',
    subCategory: 'DatePicker',
    level: 'L1',
    prompt: '创建一个日期选择器',
    expectedComponent: 'DatePicker',
    expectedProps: [],
  },
  {
    id: 'datepicker-002',
    name: 'DatePicker - 带时间选择',
    category: 'component',
    subCategory: 'DatePicker',
    level: 'L1',
    prompt: '创建一个可以选时间的日期选择器',
    expectedComponent: 'DatePicker',
    expectedProps: ['showTime'],
  },
  {
    id: 'datepicker-003',
    name: 'DatePicker - 禁用日期',
    category: 'component',
    subCategory: 'DatePicker',
    level: 'L1',
    prompt: '创建一个禁用今天之前日期的选择器',
    expectedComponent: 'DatePicker',
    expectedProps: ['disabledDate'],
  },

  // ==================== Upload ====================
  {
    id: 'upload-001',
    name: 'Upload - 基础上传',
    category: 'component',
    subCategory: 'Upload',
    level: 'L1',
    prompt: '创建一个文件上传组件',
    expectedComponent: 'Upload',
    expectedProps: ['action'],
  },
  {
    id: 'upload-002',
    name: 'Upload - 多图上传',
    category: 'component',
    subCategory: 'Upload',
    level: 'L1',
    prompt: '创建一个支持多文件上传的组件',
    expectedComponent: 'Upload',
    expectedProps: ['multiple'],
  },
  {
    id: 'upload-003',
    name: 'Upload - 图片卡片',
    category: 'component',
    subCategory: 'Upload',
    level: 'L1',
    prompt: '创建一个图片卡片风格上传组件',
    expectedComponent: 'Upload',
    expectedProps: ['listType'],
  },

  // ==================== Tree ====================
  {
    id: 'tree-001',
    name: 'Tree - 基础树',
    category: 'component',
    subCategory: 'Tree',
    level: 'L1',
    prompt: '创建一个树形控件，显示层级数据',
    expectedComponent: 'Tree',
    expectedProps: ['treeData'],
  },
  {
    id: 'tree-002',
    name: 'Tree - 可选中树',
    category: 'component',
    subCategory: 'Tree',
    level: 'L1',
    prompt: '创建一个支持勾选的树形控件',
    expectedComponent: 'Tree',
    expectedProps: ['checkable'],
  },
  {
    id: 'tree-003',
    name: 'Tree - 可拖拽树',
    category: 'component',
    subCategory: 'Tree',
    level: 'L1',
    prompt: '创建一个支持拖拽的树形控件',
    expectedComponent: 'Tree',
    expectedProps: ['draggable'],
  },

  // ==================== Avatar ====================
  {
    id: 'avatar-001',
    name: 'Avatar - 基础头像',
    category: 'component',
    subCategory: 'Avatar',
    level: 'L1',
    prompt: '创建一个头像组件，显示图片',
    expectedComponent: 'Avatar',
    expectedProps: ['src'],
  },
  {
    id: 'avatar-002',
    name: 'Avatar - 图标头像',
    category: 'component',
    subCategory: 'Avatar',
    level: 'L1',
    prompt: '创建一个显示图标的头像',
    expectedComponent: 'Avatar',
    expectedProps: ['icon'],
  },
  {
    id: 'avatar-003',
    name: 'Avatar - 方形头像',
    category: 'component',
    subCategory: 'Avatar',
    level: 'L1',
    prompt: '创建一个方形形状的头像',
    expectedComponent: 'Avatar',
    expectedProps: ['shape'],
  },

  // ==================== Badge ====================
  {
    id: 'badge-001',
    name: 'Badge - 基础徽标',
    category: 'component',
    subCategory: 'Badge',
    level: 'L1',
    prompt: '创建一个带数字徽标的组件',
    expectedComponent: 'Badge',
    expectedProps: ['count'],
  },
  {
    id: 'badge-002',
    name: 'Badge - 点状徽标',
    category: 'component',
    subCategory: 'Badge',
    level: 'L1',
    prompt: '创建一个红点状态的徽标',
    expectedComponent: 'Badge',
    expectedProps: ['dot'],
  },

  // ==================== Tag ====================
  {
    id: 'tag-001',
    name: 'Tag - 基础标签',
    category: 'component',
    subCategory: 'Tag',
    level: 'L1',
    prompt: '创建一个标签组件，显示文本"标签"',
    expectedComponent: 'Tag',
    expectedProps: [],
  },
  {
    id: 'tag-002',
    name: 'Tag - 彩色标签',
    category: 'component',
    subCategory: 'Tag',
    level: 'L1',
    prompt: '创建一个红色标签',
    expectedComponent: 'Tag',
    expectedProps: ['color'],
  },
  {
    id: 'tag-003',
    name: 'Tag - 可关闭标签',
    category: 'component',
    subCategory: 'Tag',
    level: 'L1',
    prompt: '创建一个可以关闭的标签',
    expectedComponent: 'Tag',
    expectedProps: ['closable'],
  },

  // ==================== Progress ====================
  {
    id: 'progress-001',
    name: 'Progress - 基础进度条',
    category: 'component',
    subCategory: 'Progress',
    level: 'L1',
    prompt: '创建一个进度条，显示 50%',
    expectedComponent: 'Progress',
    expectedProps: ['percent'],
  },
  {
    id: 'progress-002',
    name: 'Progress - 环形进度条',
    category: 'component',
    subCategory: 'Progress',
    level: 'L1',
    prompt: '创建一个环形进度条',
    expectedComponent: 'Progress',
    expectedProps: ['type'],
  },

  // ==================== Spin ====================
  {
    id: 'spin-001',
    name: 'Spin - 基础加载',
    category: 'component',
    subCategory: 'Spin',
    level: 'L1',
    prompt: '创建一个加载中旋转组件',
    expectedComponent: 'Spin',
    expectedProps: ['spinning'],
  },

  // ==================== Divider ====================
  {
    id: 'divider-001',
    name: 'Divider - 基础分割线',
    category: 'component',
    subCategory: 'Divider',
    level: 'L1',
    prompt: '创建一个水平分割线',
    expectedComponent: 'Divider',
    expectedProps: [],
  },
  {
    id: 'divider-002',
    name: 'Divider - 垂直分割线',
    category: 'component',
    subCategory: 'Divider',
    level: 'L1',
    prompt: '创建一个垂直分割线',
    expectedComponent: 'Divider',
    expectedProps: ['type'],
  },

  // ==================== Space ====================
  {
    id: 'space-001',
    name: 'Space - 基础间距',
    category: 'component',
    subCategory: 'Space',
    level: 'L1',
    prompt: '创建一个水平间距布局组件',
    expectedComponent: 'Space',
    expectedProps: [],
  },
  {
    id: 'space-002',
    name: 'Space - 垂直间距',
    category: 'component',
    subCategory: 'Space',
    level: 'L1',
    prompt: '创建一个垂直间距布局',
    expectedComponent: 'Space',
    expectedProps: ['direction'],
  },
];

/**
 * 组件测试用例 - L2 级别（多属性组合测试）
 */
export const componentCasesL2: TestCase[] = [
  // ==================== Button 组合 ====================
  {
    id: 'button-l2-001',
    name: 'Button - 加载中的危险按钮',
    category: 'component',
    subCategory: 'Button',
    level: 'L2',
    prompt: '创建一个加载中状态的危险类型按钮',
    expectedComponent: 'Button',
    expectedProps: ['loading', 'danger', 'type'],
  },
  {
    id: 'button-l2-002',
    name: 'Button - 带图标的块级主按钮',
    category: 'component',
    subCategory: 'Button',
    level: 'L2',
    prompt: '创建一个 primary 类型的块级按钮，带图标',
    expectedComponent: 'Button',
    expectedProps: ['type', 'block', 'icon'],
  },

  // ==================== Input 组合 ====================
  {
    id: 'input-l2-001',
    name: 'Input - 带清除和密码切换',
    category: 'component',
    subCategory: 'Input',
    level: 'L2',
    prompt: '创建一个带清除按钮的密码输入框，最大长度 20',
    expectedComponent: 'Input',
    expectedProps: ['allowClear', 'type', 'maxLength'],
  },
  {
    id: 'input-l2-002',
    name: 'Input - 带前后缀的搜索框',
    category: 'component',
    subCategory: 'Input',
    level: 'L2',
    prompt: '创建一个带搜索图标前缀和清除按钮的输入框',
    expectedComponent: 'Input',
    expectedProps: ['prefix', 'suffix', 'allowClear'],
  },

  // ==================== Form 组合 ====================
  {
    id: 'form-l2-001',
    name: 'Form - 垂直布局带验证',
    category: 'component',
    subCategory: 'Form',
    level: 'L2',
    prompt: '创建一个垂直布局的表单，包含用户名和密码两个必填项',
    expectedComponent: 'Form',
    expectedProps: ['layout'],
  },
  {
    id: 'form-l2-002',
    name: 'Form - 内联表单',
    category: 'component',
    subCategory: 'Form',
    level: 'L2',
    prompt: '创建一个内联布局的搜索表单',
    expectedComponent: 'Form',
    expectedProps: ['layout'],
  },

  // ==================== Table 组合 ====================
  {
    id: 'table-l2-001',
    name: 'Table - 带边框和分页',
    category: 'component',
    subCategory: 'Table',
    level: 'L2',
    prompt: '创建一个带边框和分页功能的表格，显示加载中状态',
    expectedComponent: 'Table',
    expectedProps: ['bordered', 'pagination', 'loading'],
  },
  {
    id: 'table-l2-002',
    name: 'Table - 可滚动表格',
    category: 'component',
    subCategory: 'Table',
    level: 'L2',
    prompt: '创建一个带横向和纵向滚动的固定表头表格',
    expectedComponent: 'Table',
    expectedProps: ['scroll'],
  },

  // ==================== Modal 组合 ====================
  {
    id: 'modal-l2-001',
    name: 'Modal - 带确认加载的弹窗',
    category: 'component',
    subCategory: 'Modal',
    level: 'L2',
    prompt: '创建一个居中显示的弹窗，标题为"确认删除"，确定按钮显示加载状态',
    expectedComponent: 'Modal',
    expectedProps: ['centered', 'confirmLoading'],
  },

  // ==================== Select 组合 ====================
  {
    id: 'select-l2-001',
    name: 'Select - 可搜索多选',
    category: 'component',
    subCategory: 'Select',
    level: 'L2',
    prompt: '创建一个支持搜索和多选的下拉选择器，带占位符',
    expectedComponent: 'Select',
    expectedProps: ['showSearch', 'mode', 'placeholder'],
  },

  // ==================== DatePicker 组合 ====================
  {
    id: 'datepicker-l2-001',
    name: 'DatePicker - 带时间的范围选择',
    category: 'component',
    subCategory: 'RangePicker',
    level: 'L2',
    prompt: '创建一个带时间选择的日期范围选择器',
    expectedComponent: 'RangePicker',
    expectedProps: ['showTime'],
  },

  // ==================== Card 组合 ====================
  {
    id: 'card-l2-001',
    name: 'Card - 带封面和操作',
    category: 'component',
    subCategory: 'Card',
    level: 'L2',
    prompt: '创建一个带封面图片、标题和底部操作栏的卡片',
    expectedComponent: 'Card',
    expectedProps: ['cover', 'title', 'actions'],
  },

  // ==================== Tabs 组合 ====================
  {
    id: 'tabs-l2-001',
    name: 'Tabs - 卡片风格可编辑',
    category: 'component',
    subCategory: 'Tabs',
    level: 'L2',
    prompt: '创建一个卡片风格的可编辑标签页，支持添加和删除',
    expectedComponent: 'Tabs',
    expectedProps: ['type'],
  },

  // ==================== Alert 组合 ====================
  {
    id: 'alert-l2-001',
    name: 'Alert - 带图标和操作',
    category: 'component',
    subCategory: 'Alert',
    level: 'L2',
    prompt: '创建一个带图标和关闭按钮的警告提示',
    expectedComponent: 'Alert',
    expectedProps: ['showIcon', 'closable'],
  },

  // ==================== Upload 组合 ====================
  {
    id: 'upload-l2-001',
    name: 'Upload - 拖拽上传多文件',
    category: 'component',
    subCategory: 'Upload',
    level: 'L2',
    prompt: '创建一个支持拖拽和多文件上传的组件，限制最多 5 个文件',
    expectedComponent: 'Upload',
    expectedProps: ['multiple', 'maxCount'],
  },

  // ==================== Tree 组合 ====================
  {
    id: 'tree-l2-001',
    name: 'Tree - 可选可拖拽',
    category: 'component',
    subCategory: 'Tree',
    level: 'L2',
    prompt: '创建一个支持勾选和拖拽的树形控件，显示连接线',
    expectedComponent: 'Tree',
    expectedProps: ['checkable', 'draggable', 'showLine'],
  },

  // ==================== Space 组合 ====================
  {
    id: 'space-l2-001',
    name: 'Space - 垂直带分割',
    category: 'component',
    subCategory: 'Space',
    level: 'L2',
    prompt: '创建一个垂直方向带分割线的间距布局',
    expectedComponent: 'Space',
    expectedProps: ['direction', 'split'],
  },
];

/**
 * 所有组件测试用例（L1 + L2）
 */
export const componentCases: TestCase[] = [
  ...componentCasesL1,
  ...componentCasesL2,
];
