import type { ComponentContract } from '../types/contract';
export * from './layout';
export * from './container';
export * from './grid';
export * from './space';
export * from './divider-flex';
export * from './button';
export * from './float-button';
export * from './typography';
export * from './tabs';
export * from './navigation';
export * from './input';
export * from './select';
export * from './form';
export * from './form-item';
export * from './data-entry-1';
export * from './data-entry-2';
export * from './data-entry-3';
export * from './data-entry-4';
export * from './card';
export * from './table';
export * from './tree';
export * from './descriptions';
export * from './data-display-1';
export * from './data-display-2';
export * from './modal';
export * from './drawer';
export * from './feedback';
export * from './other';
export declare const builtinContracts: ComponentContract[];
export declare const builtinContractMap: Record<string, ComponentContract>;
export declare function getBuiltinContract(componentType: string): ComponentContract | undefined;
//# sourceMappingURL=index.d.ts.map